server:
  port: 8090
  servlet:
    context-path: /washme

# spring
spring:
  application:
    name: '@project.artifactId@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_wash?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
